### PR TITLE
Fix wiremocks errors

### PR DESCRIPTION
**Pull request by KamilAdshare**

### CODE REVIEW

**Comment by adshares-tech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [campaign-list.component.html#L133](https://github.com/adshares/adpanel/blob/63369dcfe4b05aa4bbce77d187bb2f0df9adc846/src/app/advertiser/campaign-list/campaign-list.component.html#L133): Add an "alt" attribute to this image. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3AImgWithoutAltCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by adshares-tech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [campaign-list.component.html#L133](https://github.com/adshares/adpanel/blob/08ecda27d9030bc419fc8a035113c3145405f64f/src/app/advertiser/campaign-list/campaign-list.component.html#L133): Add an "alt" attribute to this image. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3AImgWithoutAltCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by adshares-tech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [campaign-list.component.html#L133](https://github.com/adshares/adpanel/blob/eb7b80dba27cf5ec39b3cbe0e01c03f9efbf9b95/src/app/advertiser/campaign-list/campaign-list.component.html#L133): Add an "alt" attribute to this image. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3AImgWithoutAltCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by adshares-tech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [campaign-list.component.html#L133](https://github.com/adshares/adpanel/blob/0bec9480f62ea9d2765ce8fb3a84a30b098390d5/src/app/advertiser/campaign-list/campaign-list.component.html#L133): Add an "alt" attribute to this image. [rule](https://sonarcloud.io/coding_rules#rule_key=Web%3AImgWithoutAltCheck)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by yodahack** [comment]
outdated

**Pull request closed without merging**
